version: "3.3"

services: 

  analitica:
    build: ./analitica/modeloFLask
    container_name: Tensorflow
    restart: always
    expose: 
      - 5000
    ports: 
      - 5000:5000

  data:
    build: ./data
    container_name: Data
    restart: always
    expose: 
      - 8001
    ports: 
      - 8001:8001

  login:
    build: ./Login/login
    container_name: Login
    restart: always
    expose: 
      - 3000
    ports: 
      - 3000:3000

  server:
    build: ./server1
    container_name: Server
    restart: always
    expose: 
      - 8000
    ports: 
      - 8000:8000    

  vista:
    build: ./vista-p1
    container_name: Vista
    restart: always
    expose: 
      - 80
    ports: 
      - 8081:80    